dist: xenial
# initialise a display
services:
  - xvfb
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -e .
  - pip install coveralls
  - pip install pyoctree # additional requirement for fast intersections
  - pip install shapely # additional requirement for 2d shapes
  - pip install pytest-cov # to get .coverage report via pytest
# command to run tests
script: pytest --cov=./ --verbose
# push coverage results to coverall
after_success:
  - coveralls
